csv_path: /content/data/asmodeus.csv
input_categoricals:
  - API
  - Stabilizers
  - Mixing chambers
input_numerics:
  - Flowrate
output_targets:
  - Mean num nm
  - Mean vol nm
dropna_required: true
use_wls: true
significant_only: true
reference_levels:
  API: Indometacin
  Stabilizers: P188
  Mixing chambers: FDmixer
