name: Tag on Merge to Master

on:
  push:
    branches:
      - master

permissions:
  contents: write
  
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tag based on commit messages
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
          default_bump: patch     # fallback if no conventional commit found
          release_branches: master
          dry_run: false

      - name: Output new tag
        run: echo "New tag is ${{ steps.tag.outputs.new_tag }}"
